[package]
name = "aoc14"
version = "0.1.0"
authors = ["Sergree <wokashi.rg@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
itertools = "0.10.0"
